add_library(binkcompat STATIC Bink/Bink.cpp)
target_include_directories(binkcompat PUBLIC Bink)
target_link_libraries(binkcompat PRIVATE Vendor::BinkDecoder SDL3::SDL3-static)
target_compile_definitions(binkcompat PRIVATE NOMINMAX)
target_compile_features(binkcompat PRIVATE cxx_std_17)

add_library(gen_audio STATIC Audio/Miles.cpp)
target_include_directories(gen_audio PUBLIC Audio/Include)
target_compile_features(gen_audio PRIVATE cxx_std_23)
target_compile_definitions(gen_audio PRIVATE _CRT_SECURE_NO_WARNINGS AL_ALEXT_PROTOTYPES)
target_link_libraries(gen_audio PRIVATE SDL3::SDL3-static OpenAL::OpenAL gen_audio_decoders)
if(WIN32)
    target_sources(gen_audio PRIVATE Windows/Audio.cpp)
endif()

add_library(gen_platform STATIC SDL/Paths.cpp SDL/Settings.cpp SDL/Input.cpp SDL/Window.cpp
    SDL/Synchronization.cpp SDL/Clock.cpp)
target_include_directories(gen_platform PUBLIC "${PROJECT_SOURCE_DIR}")
target_compile_features(gen_platform PRIVATE cxx_std_23)
target_compile_definitions(gen_platform PRIVATE GEN_GAME_NAME="${GEN_GAME}")
target_link_libraries(gen_platform PRIVATE SDL3::SDL3-static)
if(WIN32)
    target_sources(gen_platform PRIVATE Windows/Input.cpp Windows/Window.cpp Windows/Synchronization.cpp Windows/Application.cpp)
    target_link_libraries(gen_platform PRIVATE shell32 advapi32 winmm comctl32)
else()
    target_sources(gen_platform PRIVATE POSIX/Application.cpp)
endif()
add_subdirectory(SDL/GPU)
