include_guard(GLOBAL)

function(gen_sdk_root name default_path)
    if(DEFINED ENV{GEN_${name}_ROOT})
        set(default_path "$ENV{GEN_${name}_ROOT}")
    endif()
    set(GEN_${name}_ROOT "${default_path}" CACHE PATH "Root of the original ${name} SDK")
endfunction()

function(gen_find_dependencies)
    gen_sdk_root(DIRECTX "${GEN_CODE_DIR}/Libraries/DX90SDK")
    gen_sdk_root(GAMESPY "${GEN_CODE_DIR}/Libraries/Source/GameSpy")
    if(NOT GEN_ENABLE_GAMESPY)
        set(GEN_GAMESPY_ROOT "${PROJECT_SOURCE_DIR}/CMake/Stubs")
    endif()
    gen_sdk_root(ZLIB "${PROJECT_SOURCE_DIR}/Vendors/ZLib-1.1.4")
    find_path(GEN_DIRECTX_INCLUDE_DIR d3dx8.h PATHS "${GEN_DIRECTX_ROOT}/include" NO_DEFAULT_PATH)
    set(missing "")
    foreach(item DIRECTX_INCLUDE_DIR)
        if(NOT GEN_${item})
            list(APPEND missing "GEN_${item}")
        endif()
    endforeach()
    if(GEN_ENABLE_GAMESPY)
        foreach(header GameSpy/Peer/peer.h GameSpy/GP/gp.h GameSpy/ghttp/ghttp.h
                GameSpy/gstats/gstats.h GameSpy/gstats/gpersist.h GameSpy/pt/pt.h
                GameSpy/serverbrowsing/sb_serverbrowsing.h GameSpy/qr2/qr2.h)
            if(NOT EXISTS "${GEN_GAMESPY_ROOT}/${header}")
                list(APPEND missing "${GEN_GAMESPY_ROOT}/${header}")
            endif()
        endforeach()
    endif()
    foreach(source adler32.c compress.c crc32.c deflate.c gzio.c infblock.c infcodes.c
            inffast.c inflate.c inftrees.c infutil.c trees.c uncompr.c zutil.c zlib.h zconf.h)
        if(NOT EXISTS "${GEN_ZLIB_ROOT}/${source}")
            list(APPEND missing "${GEN_ZLIB_ROOT}/${source}")
        endif()
    endforeach()
    if(missing)
        list(JOIN missing "\n  " details)
        message(FATAL_ERROR "Missing original SDK files:\n  ${details}\nSet GEN_<SDK>_ROOT.")
    endif()
endfunction()
