include_guard(GLOBAL)

function(gen_sdk_root name default_path)
    if(DEFINED ENV{GEN_${name}_ROOT})
        set(default_path "$ENV{GEN_${name}_ROOT}")
    endif()
    set(GEN_${name}_ROOT "${default_path}" CACHE PATH "Root of the original ${name} SDK")
endfunction()

function(gen_find_dependencies)
    gen_sdk_root(DIRECTX "${GEN_CODE_DIR}/Libraries/DX90SDK")
    gen_sdk_root(MILES "${GEN_CODE_DIR}/Libraries/Source/WWVegas/Miles6")
    gen_sdk_root(GAMESPY "${GEN_CODE_DIR}/Libraries/Source/GameSpy")
    if(NOT GEN_ENABLE_GAMESPY)
        set(GEN_GAMESPY_ROOT "${PROJECT_SOURCE_DIR}/cmake/stubs")
    endif()
    gen_sdk_root(ZLIB "${PROJECT_SOURCE_DIR}/vendors/zlib-1.1.4")
    gen_sdk_root(LZH "${GEN_CODE_DIR}/Libraries/Source/Compression/LZHCompress")
    gen_sdk_root(BENCHMARK "${GEN_CODE_DIR}/Libraries/Source/Benchmark")
    gen_sdk_root(PLATFORM_SDK "")
    gen_sdk_root(SAFEDISC "${GEN_CODE_DIR}/GameEngine/Include/Common/SafeDisc")
    find_path(GEN_SAFEDISC_INCLUDE_DIR CdaPfn.h
        PATHS "${GEN_SAFEDISC_ROOT}" "${GEN_SAFEDISC_ROOT}/include" NO_DEFAULT_PATH)
    find_library(GEN_DBGHELP_LIBRARY NAMES dbghelp
        PATHS "${GEN_PLATFORM_SDK_ROOT}/Lib" "${GEN_PLATFORM_SDK_ROOT}/Lib/x86" ENV LIB)

    find_path(GEN_DIRECTX_INCLUDE_DIR d3dx8.h PATHS "${GEN_DIRECTX_ROOT}/include" NO_DEFAULT_PATH)
    foreach(lib d3dx8 d3d8 dinput8 dxguid dsound)
        find_library(GEN_DIRECTX_${lib}_LIBRARY NAMES ${lib}
            PATHS "${GEN_DIRECTX_ROOT}/lib" "${GEN_DIRECTX_ROOT}/lib/x86" NO_DEFAULT_PATH)
    endforeach()
    find_path(GEN_MILES_INCLUDE_DIR mss.h PATHS "${GEN_MILES_ROOT}/include" NO_DEFAULT_PATH)
    find_library(GEN_MILES_LIBRARY NAMES mss32
        PATHS "${GEN_MILES_ROOT}/lib/win" "${GEN_MILES_ROOT}/lib" "${GEN_MILES_ROOT}/win" NO_DEFAULT_PATH)
    find_file(GEN_MILES_CLEANUP_SOURCE NAMES cleanup.c
        PATHS "${GEN_MILES_ROOT}/win" "${GEN_MILES_ROOT}" NO_DEFAULT_PATH)

    set(missing "")
    foreach(item DIRECTX_INCLUDE_DIR DIRECTX_d3dx8_LIBRARY DIRECTX_d3d8_LIBRARY
            DIRECTX_dinput8_LIBRARY DIRECTX_dxguid_LIBRARY DIRECTX_dsound_LIBRARY)
        if(NOT GEN_${item})
            list(APPEND missing "GEN_${item}")
        endif()
    endforeach()
    if(NOT GEN_CORE_ONLY)
        if(GEN_GAME STREQUAL "ZeroHour" AND GEN_ENABLE_SAFEDISC AND NOT GEN_SAFEDISC_INCLUDE_DIR)
            list(APPEND missing "GEN_SAFEDISC_INCLUDE_DIR (CdaPfn.h)")
        endif()
        foreach(item MILES_INCLUDE_DIR MILES_LIBRARY DBGHELP_LIBRARY)
            if(NOT GEN_${item})
                list(APPEND missing "GEN_${item}")
            endif()
        endforeach()
        if(GEN_ENABLE_GAMESPY)
            foreach(header GameSpy/Peer/peer.h GameSpy/GP/gp.h GameSpy/ghttp/ghttp.h
                    GameSpy/gstats/gstats.h GameSpy/gstats/gpersist.h GameSpy/pt/pt.h
                    GameSpy/serverbrowsing/sb_serverbrowsing.h GameSpy/qr2/qr2.h)
                if(NOT EXISTS "${GEN_GAMESPY_ROOT}/${header}")
                    list(APPEND missing "${GEN_GAMESPY_ROOT}/${header}")
                endif()
            endforeach()
        endif()
        foreach(source adler32.c compress.c crc32.c deflate.c gzio.c infblock.c infcodes.c
                inffast.c inflate.c inftrees.c infutil.c trees.c uncompr.c zutil.c zlib.h zconf.h)
            if(NOT EXISTS "${GEN_ZLIB_ROOT}/${source}")
                list(APPEND missing "${GEN_ZLIB_ROOT}/${source}")
            endif()
        endforeach()
        if(GEN_ENABLE_LZH)
            foreach(source Huff.cpp Lz.cpp Lzhl.cpp Lzhl_tcp.cpp)
                if(NOT EXISTS "${GEN_LZH_ROOT}/CompLibSource/${source}")
                    list(APPEND missing "${GEN_LZH_ROOT}/CompLibSource/${source}")
                endif()
            endforeach()
            if(NOT EXISTS "${GEN_LZH_ROOT}/CompLibHeader/lzhl.h")
                list(APPEND missing "${GEN_LZH_ROOT}/CompLibHeader/lzhl.h")
            endif()
        endif()
        if(GEN_ENABLE_BENCHMARK)
            foreach(source benchmark.h emfloat.c misc.c nbench0.c nbench1.c sysspec.c)
                if(NOT EXISTS "${GEN_BENCHMARK_ROOT}/${source}")
                    list(APPEND missing "${GEN_BENCHMARK_ROOT}/${source}")
                endif()
            endforeach()
        endif()
    endif()
    if(missing)
        list(JOIN missing "\n  " details)
        message(FATAL_ERROR "Missing original SDK files:\n  ${details}\nSet GEN_<SDK>_ROOT. GameSpy, LZH and BYTEmark can be disabled with GEN_ENABLE_<SDK>=OFF. GEN_CORE_ONLY builds the standalone Westwood libraries without a game executable.")
    endif()
endfunction()
